### ISSUE TITLE
Upgrade to PHP 8.3

### ISSUE THREAD

**Issue by BenoitDD-URIOS** [diablomedia/zf1#310]
Hello,

is an update planned for PHP 8.3?
How can we help?

What methods and tools do you use to maintain the **75** zf1 repositories?

Thanks for this fork!

**Comment by jaydiablo** [comment]
@BenoitDD-URIOS just released a new version that should install on PHP 8.3. All tests pass against 8.3. Let me know if you have any issues.

**Comment by BenoitDD-URIOS** [comment]
Wow!

We'll test it out.
You're doing a great job on this fork.

Thanks again @jaydiablo
